# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c47b7553e04e3abc0b5f9962d35b622e954c91015f81374c991648068da12dfff01db7626906b8523c5436b876e7f898a4c267ccf1574b6846bef7e3015de77a

test:
  secret_key_base: 47ea84ce62e8754d7e4ee873a18c4768848c8bbe8ebaf49e9a6c5b86192124bcddd9666ee9d9926f77a6c3350d26e9d6768b0ec2c30ad8c8e58d38a3360964b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
